### ISSUE TITLE
Memory is leaking

### ISSUE THREAD

**Issue by jurgelenas** [Buzzvil/ghost-town#10]
Hello,

When a trivial expressjs app is running with ghost-town my app memory is leaking. Do you have same issues on production?

![screen shot 2015-02-21 at 10 12 47 pm](https://cloud.githubusercontent.com/assets/1081265/6315801/cad331d8-ba16-11e4-932d-da2428ad93ac.png)

**Comment by tkazec** [comment]
We have a high-load production app that processes a significant amount of large strings and binary buffers, and have never seen issues even after weeks of uptime.

What is the initial (after ~60s) memory usage of your app? How much memory do you have available on the system? Looks like node is being super lazy about garbage collection...

**Comment by jurgelenas** [comment]
It is running on standard heroku dynos which have 515Mb RAM.

After ~60s it consumes about ~300Mb RAM.

**Comment by tkazec** [comment]
Looks to me like there's no memory *leak*, then, because an actual leak will cause Heroku to restart your app after a while. As long as Node eventually cleans up, it should be fine, right?

300MB seems like quite a lot though. Our production app never goes above 80MB. Is Heroku counting the PhantomJS processes in that graph?

**Comment by jurgelenas** [comment]
Yes, Heroku is counting the PhantonJS processes in that graph too.

Maybe Phantomjs is responsible for memory leaks, not nodejs?

**Comment by tkazec** [comment]
PhantomJS leaks loads of memory, which Ghost Town helps a lot with. I'm guessing each drop in your graph is a worker being restarted. You can configure how often this happens. What are your Ghost Town settings?

**Comment by jurgelenas** [comment]
Hmmm. I will try spend more time debugging my app.

I was including ghost-town package twice in my app: one time in server.js and one time in my expressjs controller. Now I have refactored my code to pass reference for my controller from server.js. I will see if this change fixed high memory consumption in a few hours.

Thank you, for your help :)

**Comment by tkazec** [comment]
I doubt that's an issue, because you're almost certainly running into leaky PhantomJS. Try adjusting the `workerCount` and `workerDeath` options to control phantom process management.

However, I do also suggest being careful about clustering multi-file codebases. Ghost Town enables Cluster wherever it's included: http://nodejs.org/api/cluster.html
